### ISSUE TITLE
Mac Chrome で特定操作でトップページが崩れる

### ISSUE THREAD

**Issue by yterajima** [toyokappa/tabimemo#249]
![tabimemo_top_page](https://user-images.githubusercontent.com/89116/39501198-785ebdd0-4df4-11e8-98c1-236a6c1b620c.png)

## 再現方法

1. Mac の Chrome で https://tabimemo.fun/ にアクセス
2. 適当なプランをクリックし遷移
3. プランを表示
4. そのままリロード
5. 「戻る」を使ってブラウザバック
6. トップページが圧縮された様子になる

## ブラウザ情報

![image](https://user-images.githubusercontent.com/89116/39501222-8e397cc6-4df4-11e8-8cf4-e727cea0175a.png)

拡張機能の影響を考慮し、chrome のプライベートモードで確認。プライベートモードでも一部の拡張は有効化しているため、お手元の環境で再現しなければこちらの環境依存の可能性もあります。

**Comment by toyokappa** [comment]
@yterajima ありがとうございます！ 私の方でも再現はできていて #234 が恐らくの原因なのですが、原因の特定までは至ってません。見た目的な問題もあるので引き続き調査して修正に努めます。

**Comment by toyokappa** [comment]
@yterajima 
JQuery.matchHeight.jsが画像の読み込みよりも早く読み込み終わってしまう点が原因かつ、今後高さの統一をJSに処理させた場合に不安定になる可能性もあるのでCSSで高さをそろえる対応で修正しました。
